name: CI

on:
  push:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff flake8 black

      - name: Run ruff
        run: ruff check . --exit-zero

      - name: Run flake8
        run: flake8 . || true

      - name: Build API Docker image
        run: docker build -f docker/Dockerfile.api -t deid-api:ci .

      - name: Coverage (tests + report)
        run: |
          pip install coverage
          coverage run -m pytest
          coverage xml
          coverage report -m

      - name: Build Worker Docker image
        run: docker build -f docker/Dockerfile.worker -t deid-worker:ci .
